package com.example.movieandsongcatalogue.data;

import android.content.Context;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;


public class DetailsRepository {


    /**
     * The Singleton instance for this repository
     */
    private static DetailsRepository INSTANCE;

    /**
     * The Context that the app is operating within
     */
    private Context context;

    /**
     * Gets the singleton {@link DetailsRepository} for use when managing {@link Detail}s
     * in the app.
     * @return The {@link DetailsRepository} to be used for managing {@link Detail}s in the app.
     */
    public static DetailsRepository getRepository(Context context){
        if (INSTANCE == null){
            synchronized (DetailsRepository.class) {
                if (INSTANCE == null)
                    INSTANCE = new DetailsRepository();
                INSTANCE.context = context;
            }
        }
        return INSTANCE;
    }

    /**
     * Returns a list containing the specified number of Tasks generated by getTask
     * @param number The number of Tasks to return
     * @return
     */
    public List<Detail> getDetail(int number){
        List<Detail> details = new ArrayList<>(number);
        for (int i = 0; i < number; i++){
            Detail d = getDetail();
            if (i == 4){
                d.setName("Movie 6376");
            }
            details.add(d);
        }
        return details;
    }

    /**
     * Returns a {@link Detail} with randomly generated info.
     * @return a {@link Detail} for tomorrow, with randomly generated details.
     */
    public Detail getDetail(){
        // create a new Task
        Detail d = new Detail();

        // A random number generator for populating the fields
        Random random = new Random();

        int id = random.nextInt(100);
        // set the name randomly
        d.setName(String.format("Movie %s", id));

        // set the description to some placeholder
        d.setDescription("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");

        return d;
    }


}
